#! more info here: https://github.com/github/issue-labeler
name: Issue labeler
on:
  issues:
    types: [opened, edited]
  pull_request:
    types: [opened, edited]

jobs:
  issue-labels:
    uses: nosportugal/github-workflows-ccoe/.github/workflows/issue-labeler.yml@main
    with:
      configuration-path: .github/issue-labeler.yml