name: MegaLinter

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  megalinter:
    name: MegaLinter
    uses: nosportugal/github-workflows-ccoe/.github/workflows/megalinter-terraform.yml@main
    secrets: inherit